name: Deploy to Digital Ocean

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Replace Environment Placeholders
        run: |
          sed -i "s|CONTENTFUL_SPACE_ID|${{ secrets.CONTENTFUL_SPACE_ID }}|g" src/environments/environment.prod.ts
          sed -i "s|CONTENTFUL_TOKEN|${{ secrets.CONTENTFUL_TOKEN }}|g" src/environments/environment.prod.ts

      - name: Install Dependencies
        run: npm ci

      - name: Build SSR App
        run: npm run build:ssr

      - name: Deploy to Droplet
        uses: appleboy/scp-action@v0.1.6
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DO_USERNAME }}
          key: ${{ secrets.DIGITALOCEAN_PRIVATE_KEY }}
          source: "dist/"
          target: "/var/www/cv"

      - name: Restart PM2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DO_USERNAME }}
          key: ${{ secrets.DIGITALOCEAN_PRIVATE_KEY }}
          script: |
            cd /var/www/cv
            pm2 reload ecosystem.config.js --env production
