name: Deploy to Digital Ocean

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Create secrets.ts
        run: |
          mkdir -p src/environments
          echo "export const CONTENTFUL_SPACE_ID = '${{ secrets.CONTENTFUL_SPACE_ID }}';" > src/environments/secrets.ts
          echo "export const CONTENTFUL_ACCESS_TOKEN = '${{ secrets.CONTENTFUL_ACCESS_TOKEN }}';" >> src/environments/secrets.ts

      - name: Install Dependencies
        run: npm ci

      - name: Build SSR App
        run: npm run build:ssr

      - name: Deploy to Droplet
        uses: appleboy/scp-action@v0.1.6
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DO_USERNAME }}
          key: ${{ secrets.DIGITALOCEAN_PRIVATE_KEY }}
          source: "dist/"
          target: "/var/www/cv"

      - name: Restart PM2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DO_USERNAME }}
          key: ${{ secrets.DIGITALOCEAN_PRIVATE_KEY }}
          script: |
            cd /var/www/cv/dist/cv/server
            pm2 restart ecosystem.config.js
