name: Deploy to Digital Ocean

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Replace Contentful Secrets
        run: |
          sed -i "s/\${CONTENTFUL_SPACE_ID}/${{ secrets.CONTENTFUL_SPACE_ID }}/g" src/environments/environment.prod.ts
          sed -i "s/\${CONTENTFUL_ACCESS_TOKEN}/${{ secrets.CONTENTFUL_ACCESS_TOKEN }}/g" src/environments/environment.prod.ts
        shell: bash

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DIGITALOCEAN_HOST }}
          username: ${{ secrets.DO_USERNAME }}
          key: ${{ secrets.DIGITALOCEAN_PRIVATE_KEY }}
          script: |
            cd /var/www/cv
            mkdir -p server-config
            echo "module.exports = {
              spaceId: '${{ secrets.CONTENTFUL_SPACE_ID }}',
              accessToken: '${{ secrets.CONTENTFUL_ACCESS_TOKEN }}',
            };" > server-config/contentful.js
            chmod 600 server-config/contentful.js
            chown -R deploy:deploy server-config
            npm ci
            npm run build:ssr
            pm2 restart cv
